### ISSUE TITLE
Questions about /orbslam3_ros_node/pose

### ISSUE THREAD

**Issue by SSZ1** [iandouglas96/asoom_oss#12]
Hi~bro. I ran the orbslam3_ros_node using my own data. And The asoom algorithm can built the map with the pose from orbslam3.But I echoed the /orbslam3_ros_node/pose from orbslam3. I found the position  in the pose varied around the value of 0 and the value is relatively small like the picture below.

![image](https://user-images.githubusercontent.com/36888758/211516275-31888a24-de7f-4858-ab74-a9a79ad20ddc.png)

I wonder if the unit of orbslam3 pose position you used isn't a meter. Or the position in pose means differently from other slam algorithms?

Thanks a lot.

**Comment by SSZ1** [comment]
And I read the code. I found you did an inverse to Orb Pose.Why is that?

**Comment by iandouglas96** [comment]
These questions should really be asked in the orbslam3_ros repo, they are not about asoom.  orbslam outputs are scaled arbitrarily because it is monocular VO, so scale can't be recovered.  The pose is inverted just because of the choice of convention used by orbslam happens to be the inverse of what I want.
